version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "America/New_York"

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "America/New_York"
