name: CI
on:
  push:
    branches:
      - master
    paths:
      - '**.java'
      - '**.gradle'
      - 'brut.apktool/apktool-lib/src/main/resources/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.java'
      - '**.gradle'
      - 'brut.apktool/apktool-lib/src/main/resources/**'
      - '.github/workflows/**'

jobs:
  build-and-test-with-Java-8-and-later:
    runs-on: ${{ matrix.os }}
    name: Build/Test (JDK ${{ matrix.java }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [8, 9, 10, 11, 12, 13, 14]

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ matrix.java }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle-

      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Build and test
        if: startsWith(matrix.os, 'windows') == true
        run: ./gradlew.bat build shadowJar proguard

      - name: Build and test
        if: startsWith(matrix.os, 'windows') != true
        run: ./gradlew build shadowJar proguard
